import Foundation

/// 从岗位 Bundle 生成可在终端直接执行的 headless 安装脚本（无需 GUI）
struct BootstrapScriptGenerator {
    func generate(
        tools: [ResolvedTool],
        postInstallSteps: [PostInstallStep],
        mirror: BrewMirror,
        enableMAS: Bool,
        skipInstalled: Bool
    ) -> String {
        var lines: [String] = [
            "#!/bin/bash",
            "# Generated by \(BrandInfo.generatedBy) — \(isoTimestamp())",
            "# 用法: chmod +x bootstrap.sh && ./bootstrap.sh",
            "# 说明: 无 GUI 一键安装脚本，等价于应用内「开始安装」",
            "set -euo pipefail",
            ""
        ]

        if mirror != .official {
            lines.append("# --- Homebrew 镜像环境变量 ---")
            for (key, value) in mirror.environmentVariables.sorted(by: { $0.key < $1.key }) {
                lines.append("export \(key)=\"\(value)\"")
            }
            lines.append("")
        }

        lines += [
            "log() { echo \"[\(BrandInfo.generatedBy)] $*\"; }",
            "",
            "# --- 确保 Homebrew ---",
            "if ! command -v brew >/dev/null 2>&1; then",
            "  log '安装 Homebrew...'",
            "  NONINTERACTIVE=1 /bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\"",
            "fi",
            "eval \"$(/opt/homebrew/bin/brew shellenv 2>/dev/null || /usr/local/bin/brew shellenv 2>/dev/null || true)\"",
            ""
        ]

        if enableMAS {
            lines += [
                "# --- 确保 mas-cli ---",
                "if ! command -v mas >/dev/null 2>&1; then",
                "  log '安装 mas-cli...'",
                "  brew install mas",
                "fi",
                ""
            ]
        }

        let selected = tools.filter(\.isSelected).sorted { $0.tool.priority < $1.tool.priority }

        lines.append("# --- 安装工具 ---")
        for resolved in selected {
            let tool = resolved.tool
            let skipPrefix = skipInstalled ? skipCheck(for: tool) : ""
            let installCmd = installCommand(for: tool, enableMAS: enableMAS)
            guard !installCmd.isEmpty else { continue }

            lines.append("log '安装: \(tool.name)'")
            if let skip = skipPrefix {
                lines.append("if \(skip); then")
                lines.append("  log '跳过（已安装）: \(tool.name)'")
                lines.append("else")
                lines.append("  \(installCmd)")
                lines.append("fi")
            } else {
                lines.append(installCmd)
            }
            lines.append("")
        }

        if !postInstallSteps.isEmpty {
            lines.append("# --- 安装后配置 ---")
            for step in postInstallSteps {
                if let skip = step.skipIf, !skip.isEmpty {
                    lines.append("if \(skip); then")
                    lines.append("  log '跳过: \(step.name)'")
                    lines.append("else")
                    lines.append("  log '配置: \(step.name)'")
                    lines.append("  # 脚本: \(step.script) — 请从 \(BrandInfo.displayNameCN).app 资源目录复制后执行")
                    lines.append("  bash \"$(dirname \"$0\")/scripts/\(step.script)\"")
                    lines.append("fi")
                } else {
                    lines.append("log '配置: \(step.name)'")
                    lines.append("bash \"$(dirname \"$0\")/scripts/\(step.script)\"")
                }
                lines.append("")
            }
        }

        lines.append("log '全部完成！'")
        return lines.joined(separator: "\n") + "\n"
    }

    private func installCommand(for tool: DevTool, enableMAS: Bool) -> String {
        switch tool.source.type {
        case .formula:
            return "brew install \(tool.source.identifier)"
        case .cask:
            return "brew install --cask \(tool.source.identifier)"
        case .mas:
            guard enableMAS else { return "" }
            return "mas install \(tool.source.identifier)"
        case .script:
            return "bash \"$(dirname \"$0\")/scripts/\(tool.source.identifier)\""
        case .link:
            return "open \"\(tool.source.identifier)\""
        }
    }

    private func skipCheck(for tool: DevTool) -> String? {
        switch tool.source.type {
        case .formula:
            return "brew list --formula | grep -qx '\(tool.source.identifier)'"
        case .cask:
            return "brew list --cask | grep -qx '\(tool.source.identifier)'"
        case .mas:
            return "mas list | grep -q '^\\s*\(tool.source.identifier)\\s'"
        case .script:
            return tool.source.args?.first
        case .link:
            return nil
        }
    }

    private func isoTimestamp() -> String {
        let formatter = ISO8601DateFormatter()
        return formatter.string(from: Date())
    }
}
