import Foundation

/// S18-12 — Brewfile ↔ Kidux 勾选差异（检测变更并建议同步）
struct BrewfileSyncDiff: Sendable, Equatable {
    let brewfilePath: String
    let onlyInBrewfile: [DevTool]
    let onlyInKidux: [DevTool]
    let unmatchedBrewLines: [String]
    let comparedAt: Date

    var hasDifferences: Bool {
        !onlyInBrewfile.isEmpty || !onlyInKidux.isEmpty
    }

    var summaryLine: String {
        guard hasDifferences else { return "Brewfile 与 Kidux 清单一致" }
        var parts: [String] = []
        if !onlyInBrewfile.isEmpty { parts.append("Brewfile 多 \(onlyInBrewfile.count)") }
        if !onlyInKidux.isEmpty { parts.append("Kidux 多 \(onlyInKidux.count)") }
        if !unmatchedBrewLines.isEmpty { parts.append("未识别 \(unmatchedBrewLines.count)") }
        return parts.joined(separator: " · ")
    }
}

enum BrewfileSyncService {
    enum SyncError: LocalizedError {
        case emptyPath
        case unreadable(String)

        var errorDescription: String? {
            switch self {
            case .emptyPath: return "请先选择 Brewfile 路径"
            case .unreadable(let path): return "无法读取 Brewfile：\(path)"
            }
        }
    }

    static func expandPath(_ raw: String) -> String {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.hasPrefix("~") {
            return (trimmed as NSString).expandingTildeInPath
        }
        return trimmed
    }

    static func compare(
        brewfilePath rawPath: String,
        catalog: [DevTool],
        kiduxSelectedIDs: Set<String>
    ) throws -> BrewfileSyncDiff {
        let path = expandPath(rawPath)
        guard !path.isEmpty else { throw SyncError.emptyPath }
        guard let content = try? String(contentsOfFile: path, encoding: .utf8) else {
            throw SyncError.unreadable(path)
        }

        let imported = BrewfileImporter.importFromFile(content: content, catalog: catalog)
        let brewIDs = Set(imported.matchedTools.map(\.id))
        let catalogByID = Dictionary(uniqueKeysWithValues: catalog.map { ($0.id, $0) })

        let onlyBrew = imported.matchedTools
            .filter { !kiduxSelectedIDs.contains($0.id) }
            .sorted { $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending }

        let onlyKidux = kiduxSelectedIDs
            .subtracting(brewIDs)
            .compactMap { catalogByID[$0] }
            .filter { $0.source.type == .formula || $0.source.type == .cask }
            .sorted { $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending }

        return BrewfileSyncDiff(
            brewfilePath: path,
            onlyInBrewfile: onlyBrew,
            onlyInKidux: onlyKidux,
            unmatchedBrewLines: imported.unmatched,
            comparedAt: Date()
        )
    }

    static func generateContent(from tools: [DevTool]) -> String {
        var lines = ["# Generated by \(BrandInfo.generatedBy)", "tap \"homebrew/cask\""]
        let sorted = tools.sorted { $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending }
        for tool in sorted {
            switch tool.source.type {
            case .formula:
                lines.append("brew \"\(tool.source.identifier)\"")
            case .cask:
                lines.append("cask \"\(tool.source.identifier)\"")
            case .mas, .script, .link:
                break
            }
        }
        return lines.joined(separator: "\n") + "\n"
    }

    static func defaultSuggestedPath() -> String {
        let home = FileManager.default.homeDirectoryForCurrentUser.path
        let candidates = [
            "\(home)/Brewfile",
            "\(home)/.Brewfile",
            "\(home)/Documents/Brewfile"
        ]
        return candidates.first { FileManager.default.fileExists(atPath: $0) } ?? "\(home)/Brewfile"
    }
}
