import Foundation

struct CatalogFile: Decodable {
    let tools: [CatalogTool]
}

struct CatalogTool: Decodable {
    let id: String
    let name: String
    let source: ToolSource
    let priority: Int?
    let required: Bool?
}

struct ToolSource: Decodable {
    let type: String
    let identifier: String
}

struct BundleFile: Decodable {
    let id: String
    let includes: [String]?
    let tools: [BundleToolRef]?
}

struct BundleToolRef: Decodable {
    let ref: String
    let required: Bool?
}

enum CatalogLoader {
    static func loadCatalog(from root: URL) throws -> [String: CatalogTool] {
        let url = RepoPaths.catalogURL(root: root)
        guard FileManager.default.fileExists(atPath: url.path) else {
            throw KiduxCLIError.fileNotFound(url.path)
        }
        let data = try Data(contentsOf: url)
        let catalog = try JSONDecoder().decode(CatalogFile.self, from: data)
        return Dictionary(uniqueKeysWithValues: catalog.tools.map { ($0.id, $0) })
    }

    static func resolveToolIDs(roleIDs: [String], root: URL) throws -> [String] {
        var seen = Set<String>()
        var ordered: [String] = []

        for roleID in roleIDs {
            try collectToolRefs(bundleID: roleID, root: root, seen: &seen, ordered: &ordered)
        }
        return ordered
    }

    static func resolveTools(roleID: String, root: URL) throws -> [CatalogTool] {
        let catalog = try loadCatalog(from: root)
        let ids = try resolveToolIDs(roleIDs: [roleID], root: root)
        return ids.compactMap { catalog[$0] }.sorted { ($0.priority ?? 999) < ($1.priority ?? 999) }
    }

    private static func collectToolRefs(
        bundleID: String,
        root: URL,
        seen: inout Set<String>,
        ordered: inout [String]
    ) throws {
        let url = RepoPaths.bundleURL(root: root, roleID: bundleID)
        guard FileManager.default.fileExists(atPath: url.path) else {
            throw KiduxCLIError.bundleNotFound(bundleID)
        }
        let bundle = try JSONDecoder().decode(BundleFile.self, from: Data(contentsOf: url))

        for include in bundle.includes ?? [] {
            try collectToolRefs(bundleID: include, root: root, seen: &seen, ordered: &ordered)
        }
        for tool in bundle.tools ?? [] {
            if seen.insert(tool.ref).inserted {
                ordered.append(tool.ref)
            }
        }
    }
}

enum BootstrapGenerator {
    static func generate(
        tools: [CatalogTool],
        root: URL,
        bundleLabel: String,
        enableMAS: Bool = true,
        skipInstalled: Bool = true
    ) -> String {
        var lines: [String] = [
            "#!/bin/bash",
            "# Generated by kidux CLI — \(ISO8601DateFormatter().string(from: Date()))",
            "# Bundle: \(bundleLabel)",
            "# 用法: chmod +x bootstrap.sh && ./bootstrap.sh",
            "set -euo pipefail",
            "",
            "log() { echo \"[kidux] $*\"; }",
            "",
            "if ! command -v brew >/dev/null 2>&1; then",
            "  log '安装 Homebrew...'",
            "  NONINTERACTIVE=1 /bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\"",
            "fi",
            "eval \"$(/opt/homebrew/bin/brew shellenv 2>/dev/null || /usr/local/bin/brew shellenv 2>/dev/null || true)\"",
            ""
        ]

        if enableMAS, tools.contains(where: { $0.source.type == "mas" }) {
            lines += [
                "if ! command -v mas >/dev/null 2>&1; then",
                "  log '安装 mas-cli...'",
                "  brew install mas",
                "fi",
                ""
            ]
        }

        lines.append("# --- 安装工具 ---")
        for tool in tools {
            guard let installCmd = installCommand(for: tool, enableMAS: enableMAS) else { continue }
            lines.append("log '安装: \(tool.name)'")
            if skipInstalled, let skip = skipCheck(for: tool) {
                lines.append("if \(skip); then")
                lines.append("  log '跳过（已安装）: \(tool.name)'")
                lines.append("else")
                lines.append("  \(installCmd)")
                lines.append("fi")
            } else {
                lines.append(installCmd)
            }
            lines.append("")
        }

        lines.append("log '全部完成！'")
        return lines.joined(separator: "\n") + "\n"
    }

    static func copyBundledScripts(to outputDirectory: URL, root: URL) throws {
        let src = RepoPaths.scriptsDirectory(root: root)
        let dst = outputDirectory.appendingPathComponent("scripts")
        try FileManager.default.createDirectory(at: dst, withIntermediateDirectories: true)
        guard let files = try? FileManager.default.contentsOfDirectory(atPath: src.path) else { return }
        for name in files where name.hasSuffix(".sh") {
            let from = src.appendingPathComponent(name)
            let to = dst.appendingPathComponent(name)
            if FileManager.default.fileExists(atPath: to.path) {
                try FileManager.default.removeItem(at: to)
            }
            try FileManager.default.copyItem(at: from, to: to)
        }
    }

    private static func installCommand(for tool: CatalogTool, enableMAS: Bool) -> String? {
        switch tool.source.type {
        case "formula":
            return "brew install \(tool.source.identifier)"
        case "cask":
            return "brew install --cask \(tool.source.identifier)"
        case "mas":
            guard enableMAS else { return nil }
            return "mas install \(tool.source.identifier)"
        case "script":
            return "bash \"$(dirname \"$0\")/scripts/\(tool.source.identifier)\""
        case "link":
            return "open \"\(tool.source.identifier)\""
        default:
            return nil
        }
    }

    private static func skipCheck(for tool: CatalogTool) -> String? {
        switch tool.source.type {
        case "formula":
            return "brew list --formula | grep -qx '\(tool.source.identifier)'"
        case "cask":
            return "brew list --cask | grep -qx '\(tool.source.identifier)'"
        case "mas":
            return "mas list | grep -q '^\\s*\(tool.source.identifier)\\s'"
        case "script", "link":
            return nil
        default:
            return nil
        }
    }
}
